Vertex reconstructor
nu-radio/NuRadioReco pull request #235
Opened 2020-06-15 09:00 UTC by christophwelling

Adds a module that reconstructs the horizontal distance and z-coordinate of the neutrino vertex. It also reconstructs the ray type by adding an empty electric field object for the channels that like detected a signal.

2020-06-15 09:47 UTC, cg-laser commented
@christophwelling I was wondering if you could prepare a small presentation describing this module? It is really difficult to review a reconstruction module just by looking at its code. Maybe you can present it next Thursday in the inicemc call?

2020-06-15 12:18 UTC, christophwelling commented
Sounds like a good idea. I will prepare a couple slides

2020-09-04 09:37 UTC, anelles requested changes
Some more documentation and then this should be fine.

2020-09-04 09:37 UTC, anelles commented on NuRadioReco/modules/neutrino2DVertexReconstructor.py
> +    def get_correlation_array_2d(self, x, z):
Document functions please.

2020-09-04 09:37 UTC, anelles commented on NuRadioReco/modules/neutrino2DVertexReconstructor.py
> +    def get_correlation_for_pos(self, d_hor, z):
Same here.

2020-09-04 09:37 UTC, anelles commented on NuRadioReco/modules/neutrino2DVertexReconstructor.py
> +    def get_signal_travel_time(self, d_hor, z, ray_type, channel_id):
Same.

2020-09-04 09:37 UTC, anelles commented on NuRadioReco/modules/neutrino2DVertexReconstructor.py
> +        corr_range = 50.*units.ns
Same here.

2020-10-21 09:26 UTC, christophwelling commented
I added the documentation you asked for.

2020-10-21 09:36 UTC, cg-laser approved these changes

2020-10-27 14:01 UTC, anelles approved these changes

2020-10-27 15:57 UTC, merged