Add quadslotv2
nu-radio/NuRadioReco pull request #287
Opened 2021-01-27 12:23 UTC by iplaisier

- The RNO-G Hpol converter (xfdtd, csv files) is added to antennapattern.py 
- The latest Vpol and Hpol are  updated in the RNO-G detector description

2021-02-01 14:54 UTC, cg-laser requested changes
I compared the new XFDTD import/conversion function with the existing ARA reader. It seems that the file format is quite similar, maybe the two parse functions could be combined? But probably not that important. 

Comparing the calculation of the effective length I find an additional "4" in the denominator. It seems correct (comparing with A.13 of the NuRadioReco paper) if the input file is the realized gain. 

Actually I think there are more things wrong. The "n" used in A.13 is the index of refraction for which the realized gain was calculated, i.e. n=1 as these simulations were done for air. But what should change is the wavelength. 
`wavelength = c / np.array(ff)` should be replaced with `wavelength = c / np.array(ff)/n`
and H should just be
`H_theta = wavelength  * (50 / (4 * np.pi * Z_0)) ** 0.5 * gain_theta ** 0.5 * np.exp(1j * phase_theta)`

The function makes a few specific assumptions for rescaling with n, it would be nicer to have this as an parameter for the conversion function. 

Can you add the assumption about the antenna orientation also to the doc string/

2021-02-01 14:54 UTC, cg-laser commented on NuRadioReco/detector/antennapattern.py
> +    with open(path_gain, 'r', encoding='mac_roman') as fin:
do you need to specify an enconding? It seems that this is mac specific.

2021-02-01 14:54 UTC, cg-laser commented
link to NuRadioReco paper: https://doi.org/10.1140/epjc/s10052-019-6971-5

2021-03-04 19:17 UTC, anelles commented
@iplaisier, please address the comments. Otherwise, this will be left behind when merging.

2021-03-10 12:32 UTC, anelles commented
@cg-laser can you re-review this?

2021-03-10 14:36 UTC, cg-laser approved these changes
I pushed a commit that refactors the code a bit to make it clearer what the underlying assumptions are. @Ilse are these the changes that we discussed via slack and is the code that you used to make the latest revision of the Hpol antenna?

2021-03-10 15:42 UTC, iplaisier commented
There was still a bug in the Hpol converter of the latest model i send you in calculating the phases (what i mentioned 2 weeks ago). This updated in this version. Furthermore it's the same and all the changes we discussed are included.

2021-03-11 15:45 UTC, merged